language: python
python:
    - "2.7"
cache: pip
    bundler: true
    custom_install: true
# cache:
#    directories:
#        - $HOME/.cache/pip
#        - /home/travis/virtualenv/python2.7 
install:
    - pip install matplotlib
    - pip install pandas 
    - pip install sqlalchemy
    - python setup.py install --user
script:
    - nosetests -s --with-coverage --cover-package=opsimsummary


