language: python
python:
    - "2.7"
install:
    - travis_wait 25 ./setup/install.sh lsst-sims-maf scipy pandas nose numpy
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source eups-setups.sh
    - setup sims_maf
    - setup healpy
    - pip install pytest
    - pip install future
    - pip install pytest-cov
    - pip install python-coveralls
    - pip install coveralls
    - pip install coverage
    - pip install matplotlib
    - pip install sqlalchemy
    - travis_wait 2 ./setup/install_opsimsummary.sh
cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 1200
script:
    - nosetests -s --with-coverage --cover-package=opsimsummary
